Repository WildCodeSchool-2024-02/JS-RemoteFR-CrewDragon-P2-Team1, pull requests merged in 2024-04, with the labels that each got.

#10 First version of the cards for the Recommanded Destinations section + First carrousel
  client/src/App.css
  client/src/App.jsx
  client/src/assets/images/blueheart.png
  client/src/assets/images/greyheart.png
  client/src/components/RecommandedCard.jsx
  client/src/components/RecommandedList.jsx
  client/src/style.scss
Labels: REVIEWED

#9 S01 us05 footer mohamed
  client/index.html
  client/src/App.jsx
  client/src/components/Footer.css
  client/src/components/Footer.jsx
Labels: CONFLICTS RESOLVED

#11 Header
  client/package.json
  client/postcss.config.js
  client/src/App.jsx
  client/src/assets/images/GlobPrewiew.png
  client/src/assets/images/about.png
  client/src/assets/images/background.webp
  client/src/assets/images/chercher.png
  client/src/assets/images/home.png
  client/src/assets/images/support.png
  client/src/components/HeaderNavMobile.jsx
  client/src/main.jsx
  client/src/routes.js
  client/src/styles.scss
  client/tailwind.config.js
Labels: CONFLICTS RESOLVED

#14 S01 US02 Pagination Recommended Section
  client/index.html
  client/package.json
  client/src/App.jsx
  client/src/components/Footer.css
  client/src/components/Pagination.jsx
  client/src/components/RecommandedCardDesktop.jsx
  client/src/components/RecommandedCardMobile.jsx
  client/src/components/RecommandedList.jsx
  client/src/styles/RecommandedSection.scss
Labels: REVIEWED

#15 Fix du css Header mobile et ajout componant header desktop
  client/package.json
  client/src/App.jsx
  client/src/assets/images/abri.png
  client/src/assets/images/courriel-de-contact.png
  client/src/assets/images/fleche.png
  client/src/assets/images/info.png
  client/src/assets/images/plage.jpg
  client/src/components/HeaderNavDesktop.jsx
  client/src/components/HeaderNavMobile.jsx
  client/src/routes.js
  client/src/styles/HeaderNavDesktop.scss
  client/src/styles/HeaderNavMobile.scss
Labels: CONFLICTS RESOLVED

#12 S01 us04 cards modals laurent
  client/src/App.jsx
  client/src/assets/images/Mexico.jpg
  client/src/assets/images/heart-svgrepo-com.svg
  client/src/assets/images/left-arrow-svgrepo-com.svg
  client/src/assets/images/sun-svgrepo-com.svg
  client/src/assets/images/water-svgrepo-com.svg
  client/src/assets/images/weather-wind-svgrepo-com.svg
  client/src/components/CardModal.css
  client/src/components/CardModal.jsx
  client/src/main.jsx
Labels: CONFLICTS

#16 Started adding the different components and adapting scss
  client/src/App.jsx
  client/src/SectionPopular.scss
  client/src/assets/images/Logo.png
  client/src/components/Footer.jsx
  client/src/components/PopularCard.jsx
  client/src/components/PopularList.jsx
  client/src/components/RecommandedCardDesktop.jsx
  client/src/components/RecommandedCardMobile.jsx
  client/src/components/RecommandedList.jsx
  client/src/components/SectionPopular.jsx
  client/src/styles/Footer.scss
  client/src/styles/SectionPopular.scss
Labels: REVIEW REQUESTED

#21 S02 US10 Integration Composants Fanny
  client/src/App.jsx
  client/src/components/CardModal.jsx
  client/src/components/CountrySelectionManager.jsx
  client/src/components/ModalManager.jsx
  client/src/components/PopularCard.jsx
  client/src/components/PopularList.jsx
  client/src/components/RecommandedCardMobile.jsx
  client/src/components/RecommandedList.jsx
  client/src/styles/CardModal.scss
  client/src/styles/Footer.scss
  client/src/styles/HeaderNavMobile.scss
  client/src/styles/RecommandedSection.scss
  client/src/styles/SectionPopular.scss
Labels: REVIEW REQUESTED

#23 create structure, scss and responsive of CardModal from 992px and above
  client/src/components/CardModal.jsx
  client/src/styles/CardModal.scss
Labels: REVIEW REQUESTED

#22 S02 US10 Responsive Petits écrans
  client/src/components/CardModal.jsx
  client/src/components/PopularList.jsx
  client/src/components/RecommandedCardDesktop.jsx
  client/src/components/RecommandedList.jsx
  client/src/styles/CardModal.scss
  client/src/styles/Footer.scss
  client/src/styles/RecommandedSection.scss
  client/src/styles/SectionPopular.scss
Labels: CONFLICTS RESOLVED, REVIEW REQUESTED

#25 fixing responsive for 992px and above
  client/src/styles/CardModal.scss
Labels: REVIEW REQUESTED

#26 FIXCSSMOBandDESK
  client/src/styles/HeaderNavDesktop.scss
  client/src/styles/HeaderNavMobile.scss
  package-lock.json
Labels: REVIEW REQUESTED

#30 S03 change display of sections fanny
  client/src/assets/hearth_blue.png
  client/src/assets/hearth_grey.png
  client/src/assets/images/Mexico.jpg
  client/src/assets/images/blueheart.png
  client/src/assets/images/greyheart.png
  client/src/components/CardModal.jsx
  client/src/components/PopularCard.jsx
  client/src/components/PopularList.jsx
  client/src/components/RecommandedCardDesktop.jsx
  client/src/components/RecommandedCardMobile.jsx
  client/src/styles/CardModal.scss
  client/src/styles/RecommandedSection.scss
  client/src/styles/SectionPopular.scss
Labels: REVIEWED

#31 S03 - Added Routes for the Contact and About sections
  client/package.json
  client/src/App.jsx
  client/src/components/HeaderNavDesktop.jsx
  client/src/components/HeaderNavMobile.jsx
  client/src/main.jsx
  client/src/pages/About.jsx
  client/src/pages/Contact.jsx
  client/src/pages/Home.jsx
  client/src/routes.js
  client/src/styles/RecommandedSection.scss
Labels: REVIEW REQUESTED

#32 Intégration de la section About via la route
  client/src/App.jsx
  client/src/pages/About.jsx
  client/src/styles/About.css
Labels: REVIEW REQUESTED

#36 mise a jours du scss
  client/src/pages/Contact.jsx
  client/src/styles/Contact.scss
Labels: REVIEWED

#38 S03 fix scss modal fanny
  client/src/components/CardModal.jsx
  client/src/styles/About.scss
  client/src/styles/CardModal.scss
Labels: REVIEW REQUESTED

#40 create destinations in home.jsx
  client/src/pages/Home.jsx
Labels: REVIEWED

#42 Changement structure + intégration barre de recherche
  client/src/App.jsx
  client/src/components/CardModal.jsx
  client/src/components/HeaderNavDesktop.jsx
  client/src/components/HeaderNavMobile.jsx
  client/src/data/destinations.js
  client/src/main.jsx
  client/src/pages/AboutList.jsx
  client/src/pages/Contact.jsx
  client/src/pages/Home.jsx
Labels: REVIEWED

#45 S03 verif fanny
  client/src/assets/images/water.svg
  client/src/assets/images/wind.svg
  client/src/components/CardModal.jsx
  client/src/data/destinations.js
  client/src/styles/CardModal.scss
Labels: REVIEW REQUESTED

#47 Added the last destinations - List is complete !!!
  client/src/data/destinations.js
Labels: REVIEW REQUESTED

#51 Last SCSS Fixes
  client/src/components/HeaderNavMobile.jsx
  client/src/components/Pagination.jsx
  client/src/components/RecommandedCardDesktop.jsx
  client/src/data/destinations.js
  client/src/data/teamMembers.js
  client/src/pages/Contact.jsx
  client/src/styles/Footer.scss
  client/src/styles/HeaderNavDesktop.scss
  client/src/styles/HeaderNavMobile.scss
  client/src/styles/RecommandedSection.scss
  client/src/styles/SectionPopular.scss
Labels: REVIEW REQUESTED

#49 Update README.md
  README.md
Labels: REVIEWED

#48 Added Local Storage to liked destinations
  client/src/components/CardModal.jsx
  client/src/components/LikeDestinationsManagers.jsx
  client/src/components/useLocalStorage.js
  client/src/data/destinations.js
Labels: REVIEWED
